#!/bin/sh
#
has_cmd() {
  command -v "$1" >/dev/null
}

VERSION="10.20230926"

debfile="git-annex-standalone_$VERSION-1.ndall+1_amd64.deb"

URL="https://github.com/datalad/git-annex/releases/download/$VERSION/$debfile"

if has_cmd 7z; then
  extractor=7z
elif has_cmd ar; then
  extractor=ar
else
  echo "needs either 7z or ar"
  exit 1
fi


shsh install -f "_shsh-recipes/${pkg}" --plain \
  -h pre="wget '$URL' && $extractor x '$debfile' && tar xvf 'data.tar'*" \
  -h post="rm -rf '$debfile' data.tar* control.tar* debian-binary" \
  -v FISH_COMPLETIONS=usr/share/fish/vendor_completions.d/git-annex.fish \
  -v BASH_COMPLETIONS=usr/share/bash-completion/completions/git-annex \
  -v ZSH_COMPLETIONS=usr/share/zsh/vendor-completions/_git-annex \
  -v BINS=usr/bin/git-annex:usr/bin/git-annex-shell \
  -v MANS_ROOT=usr/share/man/man1
